[dev]
  command = "yarn start" # Command to start your dev server
  targetPort = 8000 # # The port for your application server, framework or site generator
  port = 8888 # The port that the netlify dev will be accessible on
  publish = "public" # If you use a _redirect file, provide the path to your static content folder